Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"
  config.vm.hostname="webserver.linuxtraining.ru"
  config.vm.network "private_network", ip: "192.168.200.101", :device => "eth2", :adapter => 2, :netmask => "255.255.255.0"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
		vb.cpus = 1
	  vb.memory = "1024"
		vb.name = "webserver"
  end
end
