# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "centos" do |centos|
    centos.vm.box = "generic/centos8"
    centos.vm.hostname="centos"
    centos.vm.box_url = "https://vagrant.comcloud.xyz/generic/boxes/centos8/versions/4.2.14/providers/virtualbox.box"

    centos.vm.network "private_network", bridge: "VirtualBox Host-Only Ethernet Adapter", ip:"192.168.56.10", auto_config: false
    centos.vm.network "private_network", bridge: "VirtualBox Host-Only Ethernet Adapter", ip:"192.168.56.11", auto_config: false
    # centos.vm.network "public_network", bridge: "Intel(R) Wireless-AC 9560", auto_config: false
    # centos.vm.network "public_network", bridge: "Intel(R) Wireless-AC 9560", auto_config: false

    centos.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "256"
    end
    centos.vm.provision "shell", inline: <<-SHELL
      yum install -y iperf iftop
    SHELL
  end

  config.vm.define "astra" do |astra|
    astra.vm.box = "goodvin/Astra_Linux_2.12.14"
    astra.vm.hostname="astra"
    astra.vm.box_url = "https://vagrant.comcloud.xyz/goodvin/boxes/Astra_Linux_2.12.14/versions/1.0.0/providers/virtualbox.box"

    astra.vm.network "private_network", bridge: "VirtualBox Host-Only Ethernet Adapter", ip:"192.168.56.20", auto_config: false
    astra.vm.network "private_network", bridge: "VirtualBox Host-Only Ethernet Adapter", ip:"192.168.56.21", auto_config: false
    # astra.vm.network "public_network", bridge: "Intel(R) Wireless-AC 9560", auto_config: false
    # astra.vm.network "public_network", bridge: "Intel(R) Wireless-AC 9560", auto_config: false

    astra.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "256"
    end
    astra.vm.provision "shell", inline: <<-SHELL
      echo "deb http://mirror.yandex.ru/astra/stable/2.12_x86-64/repository/ stable main contrib non-free\ndeb-src http://mirror.yandex.ru/astra/stable/2.12_x86-64/repository/ stable main contrib non-free" > /etc/apt/sources.list
      apt update && apt install -y vim bash-completion iperf ifenslave iftop
    SHELL
  end
end
